[package]
name = "tt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
ron = "0.8"
anyhow = "1"
rand = "0.8"

[profile.release]
panic = "abort"
debug = true
lto = true
opt-level = "s"
